import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1480, height: 940 }, deviceScaleFactor: 2 })
await page.goto('http://127.0.0.1:8777', { waitUntil: 'domcontentloaded' })
await page.waitForSelector('.appbar', { timeout: 40000 })
await page.waitForTimeout(1500)
await page.screenshot({ path: '/tmp/ui-workspace.png' })
await page.click('.nav .tab >> text=知识库')
await page.waitForSelector('.kb-cols', { timeout: 20000 })
await page.waitForTimeout(800)
await page.screenshot({ path: '/tmp/ui-kb.png' })
await page.click('.nav .tab >> text=工作台')
await page.waitForSelector('.airail, .compose-input', { timeout: 10000 })
await page.click('.compose-input')
await page.type('.compose-input', '退货率最高的 10 个产品')
await page.click('.airail .send')
await page.waitForSelector('.sql, .text', { timeout: 60000 }).catch(() => {})
await page.waitForTimeout(2000)
await page.screenshot({ path: '/tmp/ui-chat.png' })
await browser.close()
console.log('shots done')
